fixing the workflows

diff --git a/.github/actions/setup-all/action.yml b/.github/actions/setup-all/action.yml
--- a/.github/actions/setup-all/action.yml
+++ b/.github/actions/setup-all/action.yml
@@ -144,10 +144,11 @@ runs:
         mamba create -y -n ${{ env.ENV_PATH }} python=${{ matrix.python-version }}
         mamba activate ${{ env.ENV_PATH }}
         echo "Running ensurepip"
-        ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.12' && 'mamba install python-dev' || 'python -m ensurepip --upgrade' }}
-        # python -m ensurepip --upgrade || echo "ensurepip failes on Windows sometimes"
+        # ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.12' && 'mamba install python-devtools libffi' || 'python -m ensurepip --upgrade' }}
+        python -m ensurepip --upgrade || echo "ensurepip failes on Windows sometimes"
         echo "Running pip"
-        python -m pip install --upgrade pip wheel mypy setuptools
+        python -m pip install --upgrade pip || echo "pip upgrade failes on Windows sometimes"
+        python -m pip install --upgrade wheel mypy setuptools
         # Install all core and a subset of CLI dependencies, that are required for tests
         python -m pip install --upgrade -r partcad/requirements.txt
         python -m pip install --upgrade -r partcad/requirements-dev.in
