Fixing workflows (#374)

diff --git a/.github/actions/setup-all/action.yml b/.github/actions/setup-all/action.yml
--- a/.github/actions/setup-all/action.yml
+++ b/.github/actions/setup-all/action.yml
@@ -5,36 +5,45 @@ inputs:
   job:
     description: "The name of the job calling this action"
     default: "default"
+  preheat_only:
+    description: "Only preheat the cache"
+    default: "false"
 
 runs:
   using: "composite"
   steps:
     ############################################## OS PREREQUISITES ################################################
-
-    # TODO(clairbee): minimize these pre-requisites by moving the VSCode build job away from the test workflow (ci.yml)
-    - name: Install prerequisites
+    - uses: awalsh128/cache-apt-pkgs-action@latest
       if: ${{ startsWith(matrix.os, 'ubuntu') }}
-      shell: bash -l {0}
-      run: |
-        sudo apt-get -q update || exit 1
-        sudo apt-get -q install -y \
-          nodejs npm \
-          libtiff5-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev \
-          libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev \
-          python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev \
-          libxml2-dev libxslt-dev \
-          libcairo2-dev pkg-config python3-dev \
-            || exit 1
+      with:
+        packages: |
+          nodejs npm
+          libtiff5-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev
+          libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
+          python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev
+          libxml2-dev libxslt-dev
+          libcairo2-dev pkg-config python3-dev
+        version: 1.0
 
     - name: Install prerequisites
       if: ${{ startsWith(matrix.os, 'macos') }}
-      shell: bash -l {0}
+      shell: bash -el {0}
       run: |
         HOMEBREW_NO_AUTO_UPDATE=1 brew install jpeg
 
+    # Cache for vcpkg
+    - name: Export GitHub Actions cache environment variables
+      uses: actions/github-script@v7
+      with:
+        script: |
+          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
+          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
+
     - name: Install prerequisites
       if: ${{ startsWith(matrix.os, 'windows') }}
-      shell: bash -l {0}
+      env:
+        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
+      shell: bash -el {0}
       run: |
         vcpkg.exe install zlib
     #     vcpkg.exe install pkgconf
@@ -48,28 +57,41 @@ runs:
     ###################################################  PYTHON  ###################################################
 
     # Miniconda
-    # - name: Cache conda
-    #   uses: actions/cache@v4
-    #   env:
-    #     # Increase this value to reset cache if etc/example-environment.yml has not changed
-    #     CACHE_NUMBER: 3
-    #   with:
-    #     enableCrossOsArchive: true
-    #     path: ${{ runner.os == 'Windows' && 'D:\conda_pkgs_dir' || '~/conda_pkgs_dir' }}
-    #     key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}
+    - name: Cache conda
+      id: conda_cache
+      uses: actions/cache@v4
+      env:
+        # Increase this value to reset cache if etc/example-environment.yml has not changed
+        CACHE_NUMBER: 5
+      with:
+        enableCrossOsArchive: true
+        path: ${{ format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
+        key: ${{ matrix.os }}-partcad-conda-${{ env.CACHE_NUMBER }}
+
+    # TODO(clairbee): Cache the conda environment?
+
+    - name: Cache Python Environment
+      uses: actions/cache@v4
+      id: python_cache
+      with:
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-pip-1-${{ hashFiles('**/requirements*') }}
+        restore-keys: |
+          ${{ runner.os }}-pip-1-
+          ${{ runner.os }}-pip-
 
     - uses: conda-incubator/setup-miniconda@v3
+      if: ${{ inputs.preheat_only != 'true' || steps.conda_cache.outputs.cache-hit != 'true' || steps.python_cache.outputs.cache-hit != 'true' }}
+      continue-on-error: true # Usually it fails while setting up the unwanted 'test' environment
       with:
         miniforge-version: 24.11.3-0
+        use-mamba: true
         channels: conda-forge,defaults
-        channel-priority: flexible
         python-version: ${{ matrix.python-version }}
-        conda-solver: classic
-        # activate-environment: env
+        activate-environment: test
         auto-activate-base: false
-        # use-only-tar-bz2: ${{ runner.os == 'Windows' && 'false' || 'true' }}
-        # pkgs-dirs: ${{ runner.os == 'Windows' && format('D:\conda_pkgs_dir_{0}', matrix.python-version) || format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
-        # pkgs-dirs: ${{ format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
+        use-only-tar-bz2: true
+        pkgs-dirs: ${{ format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
 
     # - uses: mamba-org/setup-micromamba@v2
     #   with:
@@ -81,43 +103,38 @@ runs:
     #     # cache-environment: true
     #     post-cleanup: "all"
 
-    # - name: Init conda
-    #   shell: bash
-    #   run: |
-    #     touch ~/.bashrc
-    #     touch ~/.bash_profile
-    #     . ~/.bashrc
-    #     . ~/.bash_profile
-    #     conda init
-
-    # - uses: actions/cache@v4
-    #   id: cache
-    #   with:
-    #     path: ~/.cache/pip
-    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
-    #     restore-keys: |
-    #       ${{ runner.os }}-pip-
-
-    # TODO(clairbee): Cache conda packages
-    # TODO(clairbee): Cache the conda environment?
+    - name: Init conda
+      if: ${{ inputs.preheat_only != 'true' || steps.conda_cache.outputs.cache-hit != 'true' || steps.python_cache.outputs.cache-hit != 'true' }}
+      shell: bash -el {0}
+      run: |
+        [[ -f ~/.bashrc ]] || touch ~/.bashrc
+        [[ -f ~/.bash_profile ]] || touch ~/.bash_profile
+        . ~/.bashrc
+        . ~/.bash_profile
+        # Sometimes in GitHub workflows, the test environment is not created from the first attempt due to networking issues
+        mamba init || (rm -rf ~/miniconda3/envs/test && mamba create -y -n test && mamba init)
 
     # Install dev dependencies
     - name: install dev dependencies
-      shell: bash -l {0}
+      if: ${{ inputs.preheat_only != 'true' || steps.conda_cache.outputs.cache-hit != 'true' || steps.python_cache.outputs.cache-hit != 'true' }}
+      shell: bash -el {0}
+      env:
+        ENV_PATH: "${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }}"
       run: |
-        # . ~/.bashrc
-        # . ~/.bash_profile
-        # conda clean --all
-        # conda clean -y -i
-        conda create -p ~/${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }} python=${{ matrix.python-version }} -y
-        conda activate ~/${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }}
-        # python -m ensurepip --upgrade
-        python -m pip install --upgrade pip wheel mypy setuptools
+        . ~/.bashrc
+        . ~/.bash_profile
+        mamba create -y -n ${{ env.ENV_PATH }} python=${{ matrix.python-version }} poetry
+        mamba activate ${{ env.ENV_PATH }}
+        python -m ensurepip --upgrade
+        python -m pip install --upgrade pip
+        python -m pip install --upgrade wheel mypy setuptools
         # Install all core and a subset of CLI dependencies, that are required for tests
-        python -m pip install -r partcad/requirements.txt
-        python -m pip install -r partcad/requirements-dev.in
-        python -m pip install -r partcad-ide-vscode/src/test/python_tests/requirements.txt
-        conda deactivate
+        python -m pip install --upgrade ./partcad
+        python -m pip install --upgrade -r partcad/requirements-dev.in
+        python -m pip install --upgrade ./partcad-cli
+        python -m pip install --upgrade -r partcad-cli/requirements-dev.txt
+        python -m pip install --upgrade -r partcad-ide-vscode/src/test/python_tests/requirements.txt
+        mamba deactivate
 
         # echo "PC_INTERNAL_STATE_DIR=$(mktemp -d)" >> $GITHUB_ENV
 
