Fix tests

diff --git a/.github/actions/setup-all/action.yml b/.github/actions/setup-all/action.yml
--- a/.github/actions/setup-all/action.yml
+++ b/.github/actions/setup-all/action.yml
@@ -31,6 +31,7 @@ runs:
       shell: bash
       run: |
         vcpkg.exe install pkgconf
+        vcpkg.exe install freetype
         vcpkg.exe install cairo
         choco uninstall StrawberryPerl -y
         # choco install pkgconfiglite
@@ -39,7 +40,8 @@ runs:
         # pacman -Syu mingw-w64-x86_64-cairo
         echo "Searching for pkgconf"
         which pkgconf || echo "pkgconf not found"
-        dir C:\
+        which pkg-config || echo "pkg-config not found"
+        dir "C:\"
         echo "C:\msys64\usr\bin" >> $ENV:PATH
         echo "C:\msys64\usr\lib\pkgconfig" >> $ENV:PKG_CONFIG_PATH
         echo "C:\msys2\mingw64\bin" >> $ENV:PATH
