fixing the workflows

diff --git a/.github/actions/setup-all/action.yml b/.github/actions/setup-all/action.yml
--- a/.github/actions/setup-all/action.yml
+++ b/.github/actions/setup-all/action.yml
@@ -135,17 +135,17 @@ runs:
       shell: bash -el {0}
       env:
         ENV_PATH: "${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }}"
-        # ENV_PATH: "${{ format('{0}env-test-{1}-{2}', runner.os == 'Windows' && 'C:\\Users\\runneradmin\\' || '~/', inputs.job, matrix.python-version) }}"
       run: |
         . ~/.bashrc
         . ~/.bash_profile
         # conda clean --all
         # conda clean -y -i
-        ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.12' && 'reg delete /f HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\3.12\\PythonPath' || ''}}
+        # ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.12' && 'reg delete /f HKEY_LOCAL_MACHINE\\SOFTWARE\\Python\\PythonCore\\3.12\\PythonPath' || ''}}
         mamba create -y -n ${{ env.ENV_PATH }} python=${{ matrix.python-version }}
         mamba activate ${{ env.ENV_PATH }}
         echo "Running ensurepip"
-        python -m ensurepip --upgrade || echo "ensurepip failes on Windows sometimes"
+        ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.12' && 'echo Skip ensurepip' || 'python -m ensurepip --upgrade' }}
+        # python -m ensurepip --upgrade || echo "ensurepip failes on Windows sometimes"
         echo "Running pip"
         python -m pip install --upgrade pip wheel mypy setuptools
         # Install all core and a subset of CLI dependencies, that are required for tests
