feat(partcad-ide-vscode): Publish PartCAD Visual Studio Code extension (#281)
* feat(partcad-ide-vscode): Add support for VS Code extension to load PartCAD packages

BREAKING CHANGE: bumpversion.toml configuration to support VS Code extension, additional files (.gitattributes, .gitignore, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json) and custom configurations for the language server.  Updated package.json dependencies, and the examples directory.

* feat: Configure Dependabot for Python, npm, and GitHub Actions

- Add Dependabot configurations for daily Python, monthly npm, and monthly GitHub Actions updates.
- Remove obsolete Dependabot configuration files.
- Update the quick-start guide for pre-commit hooks.
- Remove obsolete support documentation, license, contributing, and security documents.
- Move release.yml to the root folder.

* fixes after rebasing

* Updated and packaged the VSCode Extension

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

* Fix tests

---------

Co-authored-by: Roman Kuzmenko <rkuz@partcad.org>

diff --git a/.github/actions/setup-all/action.yml b/.github/actions/setup-all/action.yml
--- a/.github/actions/setup-all/action.yml
+++ b/.github/actions/setup-all/action.yml
@@ -1,40 +1,111 @@
 name: "Setup all"
 description: "Prepare the runner no matter what the job is"
 
+inputs:
+  job:
+    description: "The name of the job calling this action"
+    default: "default"
+
 runs:
   using: "composite"
   steps:
     ############################################## OS PREREQUISITES ################################################
 
+    # TODO(clairbee): minimize these pre-requisites by moving the VSCode build job away from the test workflow (ci.yml)
     - name: Install prerequisites
       if: ${{ startsWith(matrix.os, 'ubuntu') }}
-      shell: bash
+      shell: bash -l {0}
       run: |
-        sudo apt-get update || exit 1
-        sudo apt-get install -y libcairo2-dev pkg-config python3-dev || exit 1
+        sudo apt-get -q update || exit 1
+        sudo apt-get -q install -y \
+          nodejs npm \
+          libtiff5-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev \
+          libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev \
+          python3-tk libharfbuzz-dev libfribidi-dev libxcb1-dev \
+          libxml2-dev libxslt-dev \
+          libcairo2-dev pkg-config python3-dev \
+            || exit 1
+
+    - name: Install prerequisites
+      if: ${{ startsWith(matrix.os, 'macos') }}
+      shell: bash -l {0}
+      run: |
+        HOMEBREW_NO_AUTO_UPDATE=1 brew install jpeg
+
+    - name: Install prerequisites
+      if: ${{ startsWith(matrix.os, 'windows') }}
+      shell: bash -l {0}
+      run: |
+        vcpkg.exe install zlib
+    #     vcpkg.exe install pkgconf
+    #     vcpkg.exe install freetype
+
+    # - name: Install prerequisites (part 2)
+    #   if: ${{ startsWith(matrix.os, 'windows') }}
+    #   shell: bash -l {0}
+    #   run: |
+    #     vcpkg.exe install cairo
+    #     choco uninstall StrawberryPerl -y
+    #     # choco install pkgconfiglite
+    #     choco install pacman
+    #     pacman -Sy pkgconf
+    #     # pacman -Syu mingw-w64-x86_64-gtk3
+    #     # pacman -Syu mingw-w64-x86_64-cairo
+    #     echo "Searching for pkg-config"
+    #     which pkgconf || echo "pkgconf not found"
+    #     which pkg-config || echo "pkg-config not found"
+    #     echo "C:\\msys64"
+    #     dir "C:\\msys64"
+    #     echo "C:\\msys64\\usr\\bin"
+    #     dir "C:\\msys64\\usr\\bin"
+    #     echo "C:\\msys64\\usr\\lib"
+    #     dir "C:\\msys64\\usr\\lib"
+    #     echo "C:\\mingw64"
+    #     dir "C:\\mingw64"
+    #     echo "C:\\mingw64\\usr\\bin"
+    #     dir "C:\\mingw64\\usr\\bin"
+    #     echo "C:\\mingw64\\usr\\lib"
+    #     dir "C:\\mingw64\\usr\\lib"
+    #     echo "C:\\msys64\\usr\\bin" >> $ENV:PATH
+    #     echo "C:\\msys64\\usr\\lib\\pkgconfig" >> $ENV:PKG_CONFIG_PATH
+    #     # echo "C:\\msys64\\mingw64\\bin" >> $ENV:PATH
+    #     # echo "C:\\msys64\\mingw64\\lib\\pkgconfig" >> $ENV:PKG_CONFIG_PATH
 
     ###################################################  PYTHON  ###################################################
 
     # Miniconda
     # - name: Cache conda
-    #   uses: actions/cache@v3
+    #   uses: actions/cache@v4
     #   env:
     #     # Increase this value to reset cache if etc/example-environment.yml has not changed
-    #     CACHE_NUMBER: 1
+    #     CACHE_NUMBER: 3
     #   with:
-    #     # enableCrossOsArchive: true
-    #     path: ~/conda_pkgs_dir
+    #     enableCrossOsArchive: true
+    #     path: ${{ runner.os == 'Windows' && 'D:\conda_pkgs_dir' || '~/conda_pkgs_dir' }}
     #     key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}
 
     - uses: conda-incubator/setup-miniconda@v3
       with:
-        # miniforge-version: 24.11.2-1
-        miniconda-version: latest
+        miniforge-version: 24.11.3-0
         channels: conda-forge,defaults
+        channel-priority: flexible
         python-version: ${{ matrix.python-version }}
+        conda-solver: classic
         # activate-environment: env
-        auto-activate-base: true
-        # use-only-tar-bz2: true
+        auto-activate-base: false
+        # use-only-tar-bz2: ${{ runner.os == 'Windows' && 'false' || 'true' }}
+        # pkgs-dirs: ${{ runner.os == 'Windows' && format('D:\conda_pkgs_dir_{0}', matrix.python-version) || format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
+        # pkgs-dirs: ${{ format('~/conda_pkgs_dir_{0}', matrix.python-version) }}
+
+    # - uses: mamba-org/setup-micromamba@v2
+    #   with:
+    #     micromamba-version: 2.0.5-0
+    #     # environment-file: environment.yml
+    #     init-shell: >-
+    #       bash
+    #       powershell
+    #     # cache-environment: true
+    #     post-cleanup: "all"
 
     # - name: Init conda
     #   shell: bash
@@ -63,14 +134,18 @@ runs:
         # . ~/.bashrc
         # . ~/.bash_profile
         # conda clean --all
-        conda create -n env-test python=${{ matrix.python-version }} -y
-        conda activate env-test
+        # conda clean -y -i
+        conda create -p ~/${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }} python=${{ matrix.python-version }} -y
+        conda activate ~/${{ format('env-test-{0}-{1}', inputs.job, matrix.python-version) }}
         # python -m ensurepip --upgrade
         python -m pip install --upgrade pip wheel mypy setuptools
         # Install all core and a subset of CLI dependencies, that are required for tests
-        python -m pip install -r partcad/requirements.txt && pip install svglib rlPyCairo renderlab
+        python -m pip install -r partcad/requirements.txt
         python -m pip install -r partcad/requirements-dev.in
+        python -m pip install -r partcad-ide-vscode/src/test/python_tests/requirements.txt
         conda deactivate
+
+        # echo "PC_INTERNAL_STATE_DIR=$(mktemp -d)" >> $GITHUB_ENV
 
     # - name: Update Homebrew
     #   if: matrix.os == 'macos-latest'
diff --git a/.github/workflows/test-dev.yml b/.github/workflows/test-dev.yml
--- a/.github/workflows/test-dev.yml
+++ b/.github/workflows/test-dev.yml
@@ -20,19 +20,60 @@ permissions:
   contents: read
 
 env:
+  VERSION: 0.7.112
   CONTAINER_REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}-devcontainer
   TOTAL_TIMEOUT: 900
   INSTALL_TIMEOUT: 300
 
 jobs:
-  poetry-install:
-    name: "Run: poetry install"
+  devcontainer:
+    name: "Build: Dev Container"
+    # TODO(clairbee): Verify how the build works for the bumpversion commit
+    # if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
     runs-on: ubuntu-24.04
-    timeout-minutes: 5
+    timeout-minutes: 10
+    permissions:
+      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+      contents: read
+      packages: write
     steps:
       - name: Checkout (GitHub)
         uses: actions/checkout@v4
+      - name: Setup Dev Container
+        id: setup
+        uses: ./.github/actions/setup-devcontainer
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ${{ env.CONTAINER_REGISTRY }}
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build Dev Container
+        uses: devcontainers/ci@v0.3
+        with:
+          imageName: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
+          imageTag: ${{ steps.setup.outputs.IMAGE_TAG }}
+          configFile: .devcontainer/devcontainer-build.json
+          push: always
+
+  poetry-install:
+    name: "Run: poetry install"
+    needs: devcontainer
+    permissions:
+      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+      contents: read
+      packages: read
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - name: Checkout (GitHub)
+        uses: actions/checkout@v4
+      - name: Setup Dev Container
+        id: setup
+        uses: ./.github/actions/setup-devcontainer
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -54,7 +95,8 @@ jobs:
       - name: "Run: poetry install"
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
             start_time=$SECONDS
@@ -77,11 +119,18 @@ jobs:
   pytest:
     name: "Run: pytest"
     runs-on: ubuntu-24.04
-    timeout-minutes: 10
+    timeout-minutes: 15
     needs: poetry-install
+    permissions:
+      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+      contents: read
+      packages: read
     steps:
       - name: Checkout (GitHub)
         uses: actions/checkout@v4
+      - name: Setup Dev Container
+        id: setup
+        uses: ./.github/actions/setup-devcontainer
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -104,13 +153,17 @@ jobs:
       - name: Run PyTest
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
+            (cd partcad-ide-vscode && poetry run nox --session setup && poetry run nox --session build_package)
+
             # TODO: Consider using common top level directory for all artifacts: 'output/$TOOL/...'
             mkdir -pv pytest-results
             poetry --no-ansi --no-interaction show --tree
-            poetry --no-ansi --no-interaction run pytest --verbose --color=no | ts -i %.S | ts -s
+            poetry --no-ansi --no-interaction run python -m pytest -x -p no:error-for-skips -p no:warnings  --ignore-glob="openscad*" --ignore-glob="partcad-ide-vscode/bundled" --dist no --verbose --color=no
+            echo DONE
 
       - name: Upload test results & coverage reports to github and codecov
         if: always()
@@ -128,7 +181,8 @@ jobs:
         if: always()
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
             if [ ! -d "allure-results" ]; then
@@ -149,11 +203,15 @@ jobs:
 
   # pre-commit:
   #   name: "Run: pre-commit"
+  #   needs: devcontainer
   #   runs-on: ubuntu-24.04
   #   timeout-minutes: 10
   #   steps:
   #     - name: Checkout (GitHub)
   #       uses: actions/checkout@v4
+  #     - name: Setup Dev Container
+  #       id: setup
+  #       uses: ./.github/actions/setup-devcontainer
 
   #     - name: Login to GitHub Container Registry
   #       uses: docker/login-action@v3
@@ -173,7 +231,9 @@ jobs:
   #     - name: Run pre-commit hooks
   #       uses: devcontainers/ci@v0.3
   #       with:
-  #         cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+  #         imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+  #         cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{env.IMAGE_NAME }}:${{ env.VERSION }}"
+  #         configFile: .devcontainer/.devcontainer.json
   #         push: never
   #         # TODO-24: Add custom @dependabot-like job to open PR to update dependencies
   #         # TODO: Run ggshield and/or other secrets scanning tools as separate job
@@ -186,13 +246,20 @@ jobs:
   behave:
     name: "Run: behave"
     runs-on: ubuntu-24.04
-    
+
     timeout-minutes: 30
 
     needs: poetry-install
+    permissions:
+      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+      contents: read
+      packages: read
     steps:
       - name: Checkout (GitHub)
         uses: actions/checkout@v4
+      - name: Setup Dev Container
+        id: setup
+        uses: ./.github/actions/setup-devcontainer
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -211,6 +278,12 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-poetry-
 
+      # For Windows only, use PowerShell to set the SSH agent service in the manual launch mode
+      - name: Set SSH Agent Service to Manual
+        if: runner.os == 'Windows'
+        run: Set-Service -Name ssh-agent -StartupType Manual
+        shell: pwsh
+
       - name: Start SSH Agent
         uses: webfactory/ssh-agent@v0.9.0
         with:
@@ -219,7 +292,8 @@ jobs:
       - name: Run Behave
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          configFile: .devcontainer/.devcontainer.json
           push: never
           env: |
             # TODO-25: Workaround for "Host key verification failed."
@@ -249,7 +323,8 @@ jobs:
         if: always()
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
             if [ ! -d "allure-results" ]; then
@@ -268,76 +343,86 @@ jobs:
           path: allure-report/
           retention-days: 7
 
-  nox:
-    strategy:
-      fail-fast: false
-      matrix:
-        # NOTE: OS below is the one which runs the container, not the one inside the container
-        # TODO: @alexanderilyin: Add more OSes via https://github.com/partcad/devcontainers-templates
-        os: [ubuntu-24.04]
-        python-version:
-          # TODO: Enable 3.10 when pytest job is deprecated
-          # - "3.10"
-          - "3.11"
-          - "3.12"
-    name: "Run: nox"
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 10
-    needs: poetry-install
-    steps:
-      - name: Checkout (GitHub)
-        uses: actions/checkout@v4
+  # nox:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # NOTE: OS below is the one which runs the container, not the one inside the container
+  #       # TODO: @alexanderilyin: Add more OSes via https://github.com/partcad/devcontainers-templates
+  #       os: [ubuntu-24.04]
+  #       python-version:
+  #         # TODO: Enable 3.10 when pytest job is deprecated
+  #         # - "3.10"
+  #         - "3.11"
+  #         - "3.12"
+  #   name: "Run: nox"
+  #   runs-on: ${{ matrix.os }}
+  #   timeout-minutes: 10
+  #   needs: poetry-install
+  #   permissions:
+  #     # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+  #     contents: read
+  #     packages: read
+  #   steps:
+  #     - name: Checkout (GitHub)
+  #       uses: actions/checkout@v4
+  #     - name: Setup Dev Container
+  #       id: setup
+  #       uses: ./.github/actions/setup-devcontainer
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.CONTAINER_REGISTRY }}
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: ${{ env.CONTAINER_REGISTRY }}
+  #         username: ${{ github.repository_owner }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Cache Python Environment
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cache/pypoetry
-            .venv
-          # TODO: @alexanderilyin: Consider including devcontainer.json in the hash
-          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-poetry-
+  #     # - name: Cache Python Environment
+  #     #   uses: actions/cache@v4
+  #     #   with:
+  #     #     path: |
+  #     #       ~/.cache/pypoetry
+  #     #       .venv
+  #     #     # TODO: @alexanderilyin: Consider including devcontainer.json in the hash
+  #     #     key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
+  #     #     restore-keys: |
+  #     #       ${{ runner.os }}-poetry-
 
-      # TODO: @alexanderilyin Add caching for: "Creating virtual environment (virtualenv) using python3.11 in .nox/pytest-3-11"
+  #     # TODO: @alexanderilyin Add caching for: "Creating virtual environment (virtualenv) using python3.11 in .nox/pytest-3-11"
 
-      - name: Run Nox
-        uses: devcontainers/ci@v0.3
-        with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
-          push: never
-          runCmd: |
-            poetry --no-ansi --no-interaction run nox --python ${{ matrix.python-version }}
+  #     - name: Run Nox
+  #       uses: devcontainers/ci@v0.3
+  #       with:
+  #         imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+  #         # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+  #         # configFile: .devcontainer/.devcontainer.json
+  #         push: never
+  #         runCmd: |
+  #           poetry --no-ansi --no-interaction run nox --noxfile dev-tools/noxfile.py --python ${{ matrix.python-version }}
 
-      # - name: Generate Allure Report
-      #   if: always()
-      #   uses: devcontainers/ci@v0.3
-      #   with:
-      #     cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
-      #     push: never
-      #     runCmd: |
-      #       if [ ! -d "allure-results" ]; then
-      #         echo "##[warning]allure-results directory not found. Skipping report generation."
-      #         exit 0
-      #       fi
-      #       if ! allure generate --config .devcontainer/allure.ymlallure-results -o allure-report; then
-      #         echo "##[warning]Allure report generation failed. This won't fail the build, but please investigate."
-      #       fi
+  #     # - name: Generate Allure Report
+  #     #   if: always()
+  #     #   uses: devcontainers/ci@v0.3
+  #     #   with:
+  #     #     cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PUBLISH_IMAGE_TAG }}"
+  #     #     configFile: .devcontainer/.devcontainer.json
+  #     #     push: never
+  #     #     runCmd: |
+  #     #       if [ ! -d "allure-results" ]; then
+  #     #         echo "##[warning]allure-results directory not found. Skipping report generation."
+  #     #         exit 0
+  #     #       fi
+  #     #       if ! allure generate --config .devcontainer/allure.ymlallure-results -o allure-report; then
+  #     #         echo "##[warning]Allure report generation failed. This won't fail the build, but please investigate."
+  #     #       fi
 
-      # - name: Publish Allure Report
-      #   if: always()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: pytest-allure-report
-      #     path: allure-report/
-      #     retention-days: 7
+  #     # - name: Publish Allure Report
+  #     #   if: always()
+  #     #   uses: actions/upload-artifact@v4
+  #     #   with:
+  #     #     name: pytest-allure-report
+  #     #     path: allure-report/
+  #     #     retention-days: 7
 
   integration-tests:
     # if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
@@ -345,9 +430,16 @@ jobs:
     runs-on: ubuntu-24.04
     timeout-minutes: 60
     needs: poetry-install
+    permissions:
+      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+      contents: read
+      packages: read
     steps:
       - name: Checkout (GitHub)
         uses: actions/checkout@v4
+      - name: Setup Dev Container
+        id: setup
+        uses: ./.github/actions/setup-devcontainer
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -370,7 +462,8 @@ jobs:
       - name: Run Acceptance Tests
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
             mkdir -pv pc-test-results
