Fix tests

diff --git a/.github/workflows/test-dev.yml b/.github/workflows/test-dev.yml
--- a/.github/workflows/test-dev.yml
+++ b/.github/workflows/test-dev.yml
@@ -29,7 +29,7 @@ env:
 jobs:
   devcontainer:
     name: "Build: Dev Container"
-    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
+    # if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
     runs-on: ubuntu-24.04
     timeout-minutes: 10
     permissions:
@@ -52,10 +52,10 @@ jobs:
 
       - name: Build Dev Container
         uses: devcontainers/ci@v0.3
-        if: steps.setup.outputs.BUILD_DEVCONTAINER == 'true'
+        # if: steps.setup.outputs.BUILD_DEVCONTAINER == 'true'
         with:
-          imageName: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}
-          imageTag: ${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}
+          imageName: ${{ env.CONTAINER_REGISTRY }}/${{ env.VERSION }}
+          imageTag: ${{ steps.setup.outputs.IMAGE_TAG }}
           configFile: .devcontainer/devcontainer-build.json
           push: always
 
@@ -95,7 +95,7 @@ jobs:
       - name: "Run: poetry install"
         uses: devcontainers/ci@v0.3
         with:
-          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+          cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
           configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
@@ -153,8 +153,8 @@ jobs:
       - name: Run PyTest
         uses: devcontainers/ci@v0.3
         with:
-          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
-          # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
           # configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
@@ -179,8 +179,8 @@ jobs:
         # if: always()
         uses: devcontainers/ci@v0.3
         with:
-          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
-          # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+          # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
           # configFile: .devcontainer/.devcontainer.json
           push: never
           runCmd: |
@@ -230,8 +230,8 @@ jobs:
   #     - name: Run pre-commit hooks
   #       uses: devcontainers/ci@v0.3
   #       with:
-  #         imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
-  #         cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+  #         imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+  #         cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{env.IMAGE_NAME }}:${{ env.VERSION }}"
   #         configFile: .devcontainer/.devcontainer.json
   #         push: never
   #         # TODO-24: Add custom @dependabot-like job to open PR to update dependencies
@@ -285,7 +285,7 @@ jobs:
       - name: Run Behave
         uses: devcontainers/ci@v0.3
         with:
-          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
           # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
           # configFile: .devcontainer/.devcontainer.json
           push: never
@@ -317,7 +317,7 @@ jobs:
         # if: always()
         uses: devcontainers/ci@v0.3
         with:
-          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
           # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
           # configFile: .devcontainer/.devcontainer.json
           push: never
@@ -338,86 +338,86 @@ jobs:
           path: allure-report/
           retention-days: 7
 
-  nox:
-    strategy:
-      fail-fast: false
-      matrix:
-        # NOTE: OS below is the one which runs the container, not the one inside the container
-        # TODO: @alexanderilyin: Add more OSes via https://github.com/partcad/devcontainers-templates
-        os: [ubuntu-24.04]
-        python-version:
-          # TODO: Enable 3.10 when pytest job is deprecated
-          # - "3.10"
-          - "3.11"
-          - "3.12"
-    name: "Run: nox"
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 10
-    needs: poetry-install
-    permissions:
-      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
-      contents: read
-      packages: read
-    steps:
-      - name: Checkout (GitHub)
-        uses: actions/checkout@v4
-      - name: Setup Dev Container
-        id: setup
-        uses: ./.github/actions/setup-devcontainer
+  # nox:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # NOTE: OS below is the one which runs the container, not the one inside the container
+  #       # TODO: @alexanderilyin: Add more OSes via https://github.com/partcad/devcontainers-templates
+  #       os: [ubuntu-24.04]
+  #       python-version:
+  #         # TODO: Enable 3.10 when pytest job is deprecated
+  #         # - "3.10"
+  #         - "3.11"
+  #         - "3.12"
+  #   name: "Run: nox"
+  #   runs-on: ${{ matrix.os }}
+  #   timeout-minutes: 10
+  #   needs: poetry-install
+  #   permissions:
+  #     # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+  #     contents: read
+  #     packages: read
+  #   steps:
+  #     - name: Checkout (GitHub)
+  #       uses: actions/checkout@v4
+  #     - name: Setup Dev Container
+  #       id: setup
+  #       uses: ./.github/actions/setup-devcontainer
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.CONTAINER_REGISTRY }}
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v3
+  #       with:
+  #         registry: ${{ env.CONTAINER_REGISTRY }}
+  #         username: ${{ github.repository_owner }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Cache Python Environment
-      #   uses: actions/cache@v4
-      #   with:
-      #     path: |
-      #       ~/.cache/pypoetry
-      #       .venv
-      #     # TODO: @alexanderilyin: Consider including devcontainer.json in the hash
-      #     key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-poetry-
+  #     # - name: Cache Python Environment
+  #     #   uses: actions/cache@v4
+  #     #   with:
+  #     #     path: |
+  #     #       ~/.cache/pypoetry
+  #     #       .venv
+  #     #     # TODO: @alexanderilyin: Consider including devcontainer.json in the hash
+  #     #     key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
+  #     #     restore-keys: |
+  #     #       ${{ runner.os }}-poetry-
 
-      # TODO: @alexanderilyin Add caching for: "Creating virtual environment (virtualenv) using python3.11 in .nox/pytest-3-11"
+  #     # TODO: @alexanderilyin Add caching for: "Creating virtual environment (virtualenv) using python3.11 in .nox/pytest-3-11"
 
-      - name: Run Nox
-        uses: devcontainers/ci@v0.3
-        with:
-          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
-          # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
-          # configFile: .devcontainer/.devcontainer.json
-          push: never
-          runCmd: |
-            poetry --no-ansi --no-interaction run nox --noxfile dev-tools/noxfile.py --python ${{ matrix.python-version }}
+  #     - name: Run Nox
+  #       uses: devcontainers/ci@v0.3
+  #       with:
+  #         imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
+  #         # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+  #         # configFile: .devcontainer/.devcontainer.json
+  #         push: never
+  #         runCmd: |
+  #           poetry --no-ansi --no-interaction run nox --noxfile dev-tools/noxfile.py --python ${{ matrix.python-version }}
 
-      # - name: Generate Allure Report
-      #   if: always()
-      #   uses: devcontainers/ci@v0.3
-      #   with:
-      #     cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PUBLISH_IMAGE_TAG }}"
-      #     configFile: .devcontainer/.devcontainer.json
-      #     push: never
-      #     runCmd: |
-      #       if [ ! -d "allure-results" ]; then
-      #         echo "##[warning]allure-results directory not found. Skipping report generation."
-      #         exit 0
-      #       fi
-      #       if ! allure generate --config .devcontainer/allure.ymlallure-results -o allure-report; then
-      #         echo "##[warning]Allure report generation failed. This won't fail the build, but please investigate."
-      #       fi
+  #     # - name: Generate Allure Report
+  #     #   if: always()
+  #     #   uses: devcontainers/ci@v0.3
+  #     #   with:
+  #     #     cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.PUBLISH_IMAGE_TAG }}"
+  #     #     configFile: .devcontainer/.devcontainer.json
+  #     #     push: never
+  #     #     runCmd: |
+  #     #       if [ ! -d "allure-results" ]; then
+  #     #         echo "##[warning]allure-results directory not found. Skipping report generation."
+  #     #         exit 0
+  #     #       fi
+  #     #       if ! allure generate --config .devcontainer/allure.ymlallure-results -o allure-report; then
+  #     #         echo "##[warning]Allure report generation failed. This won't fail the build, but please investigate."
+  #     #       fi
 
-      # - name: Publish Allure Report
-      #   if: always()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: pytest-allure-report
-      #     path: allure-report/
-      #     retention-days: 7
+  #     # - name: Publish Allure Report
+  #     #   if: always()
+  #     #   uses: actions/upload-artifact@v4
+  #     #   with:
+  #     #     name: pytest-allure-report
+  #     #     path: allure-report/
+  #     #     retention-days: 7
 
   integration-tests:
     # if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
@@ -457,7 +457,7 @@ jobs:
       - name: Run Acceptance Tests
         uses: devcontainers/ci@v0.3
         with:
-          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
+          imageName: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.IMAGE_TAG }}"
           # cacheFrom: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.setup.outputs.PUBLISH_IMAGE_TAG }}"
           # configFile: .devcontainer/.devcontainer.json
           push: never
