Trying to fix "docker pull" on Windows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -103,35 +103,6 @@ jobs:
         with:
           job: pytest
 
-      - name: Logout from ghcr.io
-        if: runner.os == 'Windows'
-        shell: bash -el {0}
-        run: |
-          docker logout ghcr.io
-          docker context ls
-          docker context use desktop-linux
-
-      # - name: Setup WSL
-      #   uses: Vampire/setup-wsl@v4
-      #   if: runner.os == 'Windows'
-
-      # - name: Set up Docker
-      #   uses: docker/setup-docker-action@v4
-
-      # - name: Reload the daemon
-      #   if: runner.os == 'Windows'
-      #   run: |
-      #     & '.\Docker Desktop.exe' -SwitchLinuxEngine
-
-      - name: Preload the images
-        if: runner.os == 'Windows'
-        shell: bash -el {0}
-        run: |
-          # C:\\Program\ Files\\Docker\\Docker\\Docker\ Desktop.exe -SwitchLinuxEngine || true
-          # 'C:\Program Files\Docker\Docker\Docker\ Desktop.exe' -SwitchLinuxEngine || true
-          # docker logout ghcr.io
-          docker pull ghcr.io/partcad/partcad-container-kicad:0.7.118
-
       - name: Test with pytest
         # env:
         #   PYTHONWARNINGS: ignore
@@ -159,135 +130,135 @@ jobs:
           codecov-files: pytest-test-results/junit.xml
           coverage-report: pytest-test-results/coverage.xml
 
-  # test-pytest-ide-vscode:
-  #   name: "Pytest (VS Code extension)"
-  #   needs:
-  #     - set-matrix
-  #     # - cache-preheat
-  #   strategy:
-  #     fail-fast: false
-  #     matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
-  #   runs-on: ${{ matrix.os }}
-  #   timeout-minutes: 20
+  test-pytest-ide-vscode:
+    name: "Pytest (VS Code extension)"
+    needs:
+      - set-matrix
+      # - cache-preheat
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 20
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #       with:
-  #         job: pytest-ide-vscode
-  #     - uses: ./.github/actions/setup-test
-  #       with:
-  #         job: pytest-ide-vscode
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+        with:
+          job: pytest-ide-vscode
+      - uses: ./.github/actions/setup-test
+        with:
+          job: pytest-ide-vscode
 
-  #     # TODO(clairbee): Move this step to the build jobs. Merge build.yml and test.yml to form a ci.yml, where this test job may 'needs' that build job
-  #     - name: Build the VS Code extension
-  #       shell: bash -el {0}
-  #       run: |
-  #         . ~/.bashrc
-  #         . ~/.bash_profile
-  #         mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
-  #         (cd partcad-ide-vscode && nox --session setup && nox --session build_package)
-  #         mamba deactivate
+      # TODO(clairbee): Move this step to the build jobs. Merge build.yml and test.yml to form a ci.yml, where this test job may 'needs' that build job
+      - name: Build the VS Code extension
+        shell: bash -el {0}
+        run: |
+          . ~/.bashrc
+          . ~/.bash_profile
+          mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
+          (cd partcad-ide-vscode && nox --session setup && nox --session build_package)
+          mamba deactivate
 
-  #     - name: Test VS Code extension with pytest
-  #       env:
-  #         PYTHONWARNINGS: ignore
-  #       shell: bash -el {0}
-  #       run: |
-  #         . ~/.bashrc
-  #         . ~/.bash_profile
-  #         mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
+      - name: Test VS Code extension with pytest
+        env:
+          PYTHONWARNINGS: ignore
+        shell: bash -el {0}
+        run: |
+          . ~/.bashrc
+          . ~/.bash_profile
+          mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
 
-  #         mkdir -pv pytest-vscode-test-results
-  #         pytest \
-  #           partcad-ide-vscode \
-  #           -x -p no:error-for-skips -p no:warnings --dist no
-  #         coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./pytest-vscode-test-results/coverage.xml
-  #         mamba deactivate
+          mkdir -pv pytest-vscode-test-results
+          pytest \
+            partcad-ide-vscode \
+            -x -p no:error-for-skips -p no:warnings --dist no
+          coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./pytest-vscode-test-results/coverage.xml
+          mamba deactivate
 
-  #     - name: Upload test results & coverage reports to github and codecov
-  #       uses: ./.github/actions/upload-test-results
-  #       with:
-  #         name: pytest-vscode-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #         path: pytest-vscode-test-results/
-  #         retention-days: 7
-  #         status: ${{ job.status }}
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         codecov-files: pytest-vscode-test-results/junit.xml
-  #         coverage-report: pytest-vscode-test-results/coverage.xml
+      - name: Upload test results & coverage reports to github and codecov
+        uses: ./.github/actions/upload-test-results
+        with:
+          name: pytest-vscode-test-results-${{matrix.os}}-${{matrix.python-version}}
+          path: pytest-vscode-test-results/
+          retention-days: 7
+          status: ${{ job.status }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+          codecov-files: pytest-vscode-test-results/junit.xml
+          coverage-report: pytest-vscode-test-results/coverage.xml
 
-  # test-behave:
-  #   name: "Behave"
-  #   needs:
-  #     - set-matrix
-  #     # - cache-preheat
-  #   strategy:
-  #     fail-fast: false
-  #     matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
-  #   runs-on: ${{ matrix.os }}
-  #   timeout-minutes: 60
+  test-behave:
+    name: "Behave"
+    needs:
+      - set-matrix
+      # - cache-preheat
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 60
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #       with:
-  #         job: behave
-  #     - uses: ./.github/actions/setup-test
-  #       with:
-  #         job: behave
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+        with:
+          job: behave
+      - uses: ./.github/actions/setup-test
+        with:
+          job: behave
 
-  #     # For Windows only, use PowerShell to set the SSH agent service in the manual launch mode
-  #     - name: Set SSH Agent Service to Manual
-  #       if: runner.os == 'Windows'
-  #       run: Set-Service -Name ssh-agent -StartupType Manual
-  #       shell: pwsh
+      # For Windows only, use PowerShell to set the SSH agent service in the manual launch mode
+      - name: Set SSH Agent Service to Manual
+        if: runner.os == 'Windows'
+        run: Set-Service -Name ssh-agent -StartupType Manual
+        shell: pwsh
 
-  #     - name: Start SSH Agent
-  #       uses: webfactory/ssh-agent@v0.9.0
-  #       with:
-  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RO }}
+      - name: Start SSH Agent
+        uses: webfactory/ssh-agent@v0.9.0
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RO }}
 
-  #     - name: Test with behave
-  #       shell: bash -el {0}
-  #       run: |
-  #         . ~/.bashrc
-  #         . ~/.bash_profile
-  #         mkdir -pv behave-test-results
+      - name: Test with behave
+        shell: bash -el {0}
+        run: |
+          . ~/.bashrc
+          . ~/.bash_profile
+          mkdir -pv behave-test-results
 
-  #         mamba activate ${{ format('env-test-behave-{0}', matrix.python-version) }}
+          mamba activate ${{ format('env-test-behave-{0}', matrix.python-version) }}
 
-  #         export PYTHONUTF8=1
-  #         export PYTHONIOENCODING=utf-8
+          export PYTHONUTF8=1
+          export PYTHONIOENCODING=utf-8
 
-  #         BEHAVE_CMD="coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave"
-  #         if [[ "$RUNNER_OS" == "Windows" ]]; then
-  #           BEHAVE_CMD="$BEHAVE_CMD --tags=-skip-windows"
-  #         fi
+          BEHAVE_CMD="coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave"
+          if [[ "$RUNNER_OS" == "Windows" ]]; then
+            BEHAVE_CMD="$BEHAVE_CMD --tags=-skip-windows"
+          fi
 
-  #         if ! eval "$BEHAVE_CMD"; then
-  #           echo "Behave tests failed"
-  #           exit 1
-  #         fi
+          if ! eval "$BEHAVE_CMD"; then
+            echo "Behave tests failed"
+            exit 1
+          fi
 
-  #         # if ! coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave; then
-  #         #   echo "Behave tests failed"
-  #         #   exit 1
-  #         # fi
+          # if ! coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave; then
+          #   echo "Behave tests failed"
+          #   exit 1
+          # fi
 
-  #         coverage combine
-  #         coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./behave-test-results/coverage.xml
-  #         mamba deactivate
+          coverage combine
+          coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./behave-test-results/coverage.xml
+          mamba deactivate
 
-  #     - name: Upload test results & coverage reports to github and codecov
-  #       uses: ./.github/actions/upload-test-results
-  #       with:
-  #         name: behave-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #         path: behave-test-results/
-  #         retention-days: 7
-  #         status: ${{ job.status }}
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         codecov-files: behave-test-results/junit.xml
-  #         coverage-report: behave-test-results/coverage.xml
+      - name: Upload test results & coverage reports to github and codecov
+        uses: ./.github/actions/upload-test-results
+        with:
+          name: behave-test-results-${{matrix.os}}-${{matrix.python-version}}
+          path: behave-test-results/
+          retention-days: 7
+          status: ${{ job.status }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+          codecov-files: behave-test-results/junit.xml
+          coverage-report: behave-test-results/coverage.xml
 
   # test-examples-partcad:
   #   name: "Examples (PartCAD)"
@@ -342,109 +313,109 @@ jobs:
   #         codecov-files: examples-partcad-test-results/junit.xml
   #         coverage-report: examples-partcad-test-results/coverage.xml
 
-  # test-examples-all:
-  #   name: "Examples (All)"
-  #   needs:
-  #     - set-matrix
-  #     # - cache-preheat
-  #   strategy:
-  #     fail-fast: false
-  #     matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
-  #   runs-on: ${{ matrix.os }}
-  #   timeout-minutes: 30
+  test-examples-all:
+    name: "Examples (All)"
+    needs:
+      - set-matrix
+      # - cache-preheat
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 30
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #       with:
-  #         job: examples-all
-  #     - uses: ./.github/actions/setup-test
-  #       with:
-  #         job: examples-all
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+        with:
+          job: examples-all
+      - uses: ./.github/actions/setup-test
+        with:
+          job: examples-all
 
-  #     - name: Basic integration test for CLI (all examples)
-  #       shell: bash -el {0}
-  #       run: |
-  #         . ~/.bashrc
-  #         . ~/.bash_profile
-  #         mkdir -pv examples-all-test-results
+      - name: Basic integration test for CLI (all examples)
+        shell: bash -el {0}
+        run: |
+          . ~/.bashrc
+          . ~/.bash_profile
+          mkdir -pv examples-all-test-results
 
-  #         mamba activate ${{ format('env-test-examples-all-{0}', matrix.python-version) }}
+          mamba activate ${{ format('env-test-examples-all-{0}', matrix.python-version) }}
 
-  #         # BEGIN ALL EXAMPLES
-  #         cd ./examples
-  #         # TODO(clairbee): Limit RAM usage by restricting the number of threads?
-  #         coverage run --rcfile=../dev-tools/coverage.rc --data-file=.coverage.1 -m partcad_cli.click.command --no-ansi list all -r //pub/examples
-  #         coverage run --rcfile=../dev-tools/coverage.rc --data-file=.coverage.2 -m partcad_cli.click.command --no-ansi test -r --package //pub/examples
-  #         coverage combine
-  #         # END ALL EXAMPLES
+          # BEGIN ALL EXAMPLES
+          cd ./examples
+          # TODO(clairbee): Limit RAM usage by restricting the number of threads?
+          coverage run --rcfile=../dev-tools/coverage.rc --data-file=.coverage.1 -m partcad_cli.click.command --no-ansi list all -r //pub/examples
+          coverage run --rcfile=../dev-tools/coverage.rc --data-file=.coverage.2 -m partcad_cli.click.command --no-ansi test -r --package //pub/examples
+          coverage combine
+          # END ALL EXAMPLES
 
-  #         coverage xml --rcfile=../dev-tools/coverage.rc --data-file=.coverage -o ../examples-all-test-results/coverage.xml
-  #         mamba deactivate
+          coverage xml --rcfile=../dev-tools/coverage.rc --data-file=.coverage -o ../examples-all-test-results/coverage.xml
+          mamba deactivate
 
-  #     - name: Upload test results & coverage reports to github and codecov
-  #       uses: ./.github/actions/upload-test-results
-  #       with:
-  #         name: examples-all-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #         path: examples-all-test-results/
-  #         retention-days: 7
-  #         status: ${{ job.status }}
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         codecov-files: examples-all-test-results/junit.xml
-  #         coverage-report: examples-all-test-results/coverage.xml
+      - name: Upload test results & coverage reports to github and codecov
+        uses: ./.github/actions/upload-test-results
+        with:
+          name: examples-all-test-results-${{matrix.os}}-${{matrix.python-version}}
+          path: examples-all-test-results/
+          retention-days: 7
+          status: ${{ job.status }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+          codecov-files: examples-all-test-results/junit.xml
+          coverage-report: examples-all-test-results/coverage.xml
 
-  # test-pub-repo:
-  #   name: "Repo //pub"
-  #   # Note: preheat is using another set of machines
-  #   # needs: cache-preheat
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: [ubuntu-24.04-l, windows-latest-l, macos-13, macos-latest]
-  #       # TODO(clairbee): Move this to the environment variables too
-  #       # os: [ubuntu-24.04-l, windows-latest-l, macos-13, macos-latest]
-  #       python-version: ["3.10", "3.12"]
-  #       exclude: [{"os": "windows-latest-l", "python-version": "3.12"}]
-  #   runs-on: ${{ matrix.os }}
-  #   if: ${{ github.ref != 'refs/heads/devel' || startsWith(github.event.head_commit.message, 'Version updated') }}
-  #   timeout-minutes: 15
+  test-pub-repo:
+    name: "Repo //pub"
+    # Note: preheat is using another set of machines
+    # needs: cache-preheat
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-24.04-l, windows-latest-l, macos-13, macos-latest]
+        # TODO(clairbee): Move this to the environment variables too
+        # os: [ubuntu-24.04-l, windows-latest-l, macos-13, macos-latest]
+        python-version: ["3.10", "3.12"]
+        exclude: [{"os": "windows-latest-l", "python-version": "3.12"}]
+    runs-on: ${{ matrix.os }}
+    if: ${{ github.ref != 'refs/heads/devel' || startsWith(github.event.head_commit.message, 'Version updated') }}
+    timeout-minutes: 15
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #       with:
-  #         job: pub-repo
-  #     - uses: ./.github/actions/setup-test
-  #       with:
-  #         job: pub-repo
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+        with:
+          job: pub-repo
+      - uses: ./.github/actions/setup-test
+        with:
+          job: pub-repo
 
-  #     - name: Test the entire repository
-  #       shell: bash -el {0}
-  #       run: |
-  #         . ~/.bashrc
-  #         . ~/.bash_profile
-  #         mkdir -pv pub-repo-test-results
+      - name: Test the entire repository
+        shell: bash -el {0}
+        run: |
+          . ~/.bashrc
+          . ~/.bash_profile
+          mkdir -pv pub-repo-test-results
 
-  #         mamba activate ${{ format('env-test-pub-repo-{0}', matrix.python-version) }}
+          mamba activate ${{ format('env-test-pub-repo-{0}', matrix.python-version) }}
 
-  #         # BEGIN PUBLIC REPO
-  #         cd examples
-  #         coverage run --rcfile=../dev-tools/coverage.rc --data-file=.coverage -m partcad_cli.click.command --no-ansi list all -r //pub
-  #         # TODO(clairbee): fix the failing packages first
-  #         # coverage run --rcfile=../dev-tools/coverage.rc -m partcad_cli.click.command --no-ansi --threads-max=4 test -r --package //pub
-  #         # END PUBLIC REPO
-  #         coverage combine
+          # BEGIN PUBLIC REPO
+          cd examples
+          coverage run --rcfile=../dev-tools/coverage.rc --data-file=.coverage -m partcad_cli.click.command --no-ansi list all -r //pub
+          # TODO(clairbee): fix the failing packages first
+          # coverage run --rcfile=../dev-tools/coverage.rc -m partcad_cli.click.command --no-ansi --threads-max=4 test -r --package //pub
+          # END PUBLIC REPO
+          coverage combine
 
-  #         coverage xml --rcfile=../dev-tools/coverage.rc --data-file=.coverage -o ../pub-repo-test-results/coverage.xml
-  #         mamba deactivate
+          coverage xml --rcfile=../dev-tools/coverage.rc --data-file=.coverage -o ../pub-repo-test-results/coverage.xml
+          mamba deactivate
 
-  #     - name: Upload test results & coverage reports to github and codecov
-  #       uses: ./.github/actions/upload-test-results
-  #       with:
-  #         name: pub-repo-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #         path: pub-repo-test-results/
-  #         retention-days: 7
-  #         status: ${{ job.status }}
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         codecov-files: pub-repo-test-results/junit.xml
-  #         coverage-report: pub-repo-test-results/coverage.xml
+      - name: Upload test results & coverage reports to github and codecov
+        uses: ./.github/actions/upload-test-results
+        with:
+          name: pub-repo-test-results-${{matrix.os}}-${{matrix.python-version}}
+          path: pub-repo-test-results/
+          retention-days: 7
+          status: ${{ job.status }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+          codecov-files: pub-repo-test-results/junit.xml
+          coverage-report: pub-repo-test-results/coverage.xml
