Trying to fix "docker pull" on Windows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -107,6 +107,9 @@ jobs:
         uses: Vampire/setup-wsl@v4
         if: runner.os == 'Windows'
 
+      - name: Set up Docker
+        uses: docker/setup-docker-action@v4
+
       - name: Preload the images
         if: runner.os == 'Windows'
         run: |
@@ -140,135 +143,135 @@ jobs:
           codecov-files: pytest-test-results/junit.xml
           coverage-report: pytest-test-results/coverage.xml
 
-  test-pytest-ide-vscode:
-    name: "Pytest (VS Code extension)"
-    needs:
-      - set-matrix
-      # - cache-preheat
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 20
+  # test-pytest-ide-vscode:
+  #   name: "Pytest (VS Code extension)"
+  #   needs:
+  #     - set-matrix
+  #     # - cache-preheat
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
+  #   runs-on: ${{ matrix.os }}
+  #   timeout-minutes: 20
 
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/setup-all
-        with:
-          job: pytest-ide-vscode
-      - uses: ./.github/actions/setup-test
-        with:
-          job: pytest-ide-vscode
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/setup-all
+  #       with:
+  #         job: pytest-ide-vscode
+  #     - uses: ./.github/actions/setup-test
+  #       with:
+  #         job: pytest-ide-vscode
 
-      # TODO(clairbee): Move this step to the build jobs. Merge build.yml and test.yml to form a ci.yml, where this test job may 'needs' that build job
-      - name: Build the VS Code extension
-        shell: bash -el {0}
-        run: |
-          . ~/.bashrc
-          . ~/.bash_profile
-          mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
-          (cd partcad-ide-vscode && nox --session setup && nox --session build_package)
-          mamba deactivate
+  #     # TODO(clairbee): Move this step to the build jobs. Merge build.yml and test.yml to form a ci.yml, where this test job may 'needs' that build job
+  #     - name: Build the VS Code extension
+  #       shell: bash -el {0}
+  #       run: |
+  #         . ~/.bashrc
+  #         . ~/.bash_profile
+  #         mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
+  #         (cd partcad-ide-vscode && nox --session setup && nox --session build_package)
+  #         mamba deactivate
 
-      - name: Test VS Code extension with pytest
-        env:
-          PYTHONWARNINGS: ignore
-        shell: bash -el {0}
-        run: |
-          . ~/.bashrc
-          . ~/.bash_profile
-          mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
+  #     - name: Test VS Code extension with pytest
+  #       env:
+  #         PYTHONWARNINGS: ignore
+  #       shell: bash -el {0}
+  #       run: |
+  #         . ~/.bashrc
+  #         . ~/.bash_profile
+  #         mamba activate ${{ format('env-test-pytest-ide-vscode-{0}', matrix.python-version) }}
 
-          mkdir -pv pytest-vscode-test-results
-          pytest \
-            partcad-ide-vscode \
-            -x -p no:error-for-skips -p no:warnings --dist no
-          coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./pytest-vscode-test-results/coverage.xml
-          mamba deactivate
+  #         mkdir -pv pytest-vscode-test-results
+  #         pytest \
+  #           partcad-ide-vscode \
+  #           -x -p no:error-for-skips -p no:warnings --dist no
+  #         coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./pytest-vscode-test-results/coverage.xml
+  #         mamba deactivate
 
-      - name: Upload test results & coverage reports to github and codecov
-        uses: ./.github/actions/upload-test-results
-        with:
-          name: pytest-vscode-test-results-${{matrix.os}}-${{matrix.python-version}}
-          path: pytest-vscode-test-results/
-          retention-days: 7
-          status: ${{ job.status }}
-          token: ${{ secrets.CODECOV_TOKEN }}
-          codecov-files: pytest-vscode-test-results/junit.xml
-          coverage-report: pytest-vscode-test-results/coverage.xml
+  #     - name: Upload test results & coverage reports to github and codecov
+  #       uses: ./.github/actions/upload-test-results
+  #       with:
+  #         name: pytest-vscode-test-results-${{matrix.os}}-${{matrix.python-version}}
+  #         path: pytest-vscode-test-results/
+  #         retention-days: 7
+  #         status: ${{ job.status }}
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         codecov-files: pytest-vscode-test-results/junit.xml
+  #         coverage-report: pytest-vscode-test-results/coverage.xml
 
-  test-behave:
-    name: "Behave"
-    needs:
-      - set-matrix
-      # - cache-preheat
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 60
+  # test-behave:
+  #   name: "Behave"
+  #   needs:
+  #     - set-matrix
+  #     # - cache-preheat
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
+  #   runs-on: ${{ matrix.os }}
+  #   timeout-minutes: 60
 
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/setup-all
-        with:
-          job: behave
-      - uses: ./.github/actions/setup-test
-        with:
-          job: behave
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: ./.github/actions/setup-all
+  #       with:
+  #         job: behave
+  #     - uses: ./.github/actions/setup-test
+  #       with:
+  #         job: behave
 
-      # For Windows only, use PowerShell to set the SSH agent service in the manual launch mode
-      - name: Set SSH Agent Service to Manual
-        if: runner.os == 'Windows'
-        run: Set-Service -Name ssh-agent -StartupType Manual
-        shell: pwsh
+  #     # For Windows only, use PowerShell to set the SSH agent service in the manual launch mode
+  #     - name: Set SSH Agent Service to Manual
+  #       if: runner.os == 'Windows'
+  #       run: Set-Service -Name ssh-agent -StartupType Manual
+  #       shell: pwsh
 
-      - name: Start SSH Agent
-        uses: webfactory/ssh-agent@v0.9.0
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RO }}
+  #     - name: Start SSH Agent
+  #       uses: webfactory/ssh-agent@v0.9.0
+  #       with:
+  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_RO }}
 
-      - name: Test with behave
-        shell: bash -el {0}
-        run: |
-          . ~/.bashrc
-          . ~/.bash_profile
-          mkdir -pv behave-test-results
+  #     - name: Test with behave
+  #       shell: bash -el {0}
+  #       run: |
+  #         . ~/.bashrc
+  #         . ~/.bash_profile
+  #         mkdir -pv behave-test-results
 
-          mamba activate ${{ format('env-test-behave-{0}', matrix.python-version) }}
+  #         mamba activate ${{ format('env-test-behave-{0}', matrix.python-version) }}
 
-          export PYTHONUTF8=1
-          export PYTHONIOENCODING=utf-8
+  #         export PYTHONUTF8=1
+  #         export PYTHONIOENCODING=utf-8
 
-          BEHAVE_CMD="coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave"
-          if [[ "$RUNNER_OS" == "Windows" ]]; then
-            BEHAVE_CMD="$BEHAVE_CMD --tags=-skip-windows"
-          fi
+  #         BEHAVE_CMD="coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave"
+  #         if [[ "$RUNNER_OS" == "Windows" ]]; then
+  #           BEHAVE_CMD="$BEHAVE_CMD --tags=-skip-windows"
+  #         fi
 
-          if ! eval "$BEHAVE_CMD"; then
-            echo "Behave tests failed"
-            exit 1
-          fi
+  #         if ! eval "$BEHAVE_CMD"; then
+  #           echo "Behave tests failed"
+  #           exit 1
+  #         fi
 
-          # if ! coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave; then
-          #   echo "Behave tests failed"
-          #   exit 1
-          # fi
+  #         # if ! coverage run --rcfile=./dev-tools/coverage.rc --data-file=.coverage -m behave; then
+  #         #   echo "Behave tests failed"
+  #         #   exit 1
+  #         # fi
 
-          coverage combine
-          coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./behave-test-results/coverage.xml
-          mamba deactivate
+  #         coverage combine
+  #         coverage xml --rcfile=./dev-tools/coverage.rc --data-file=.coverage -o ./behave-test-results/coverage.xml
+  #         mamba deactivate
 
-      - name: Upload test results & coverage reports to github and codecov
-        uses: ./.github/actions/upload-test-results
-        with:
-          name: behave-test-results-${{matrix.os}}-${{matrix.python-version}}
-          path: behave-test-results/
-          retention-days: 7
-          status: ${{ job.status }}
-          token: ${{ secrets.CODECOV_TOKEN }}
-          codecov-files: behave-test-results/junit.xml
-          coverage-report: behave-test-results/coverage.xml
+  #     - name: Upload test results & coverage reports to github and codecov
+  #       uses: ./.github/actions/upload-test-results
+  #       with:
+  #         name: behave-test-results-${{matrix.os}}-${{matrix.python-version}}
+  #         path: behave-test-results/
+  #         retention-days: 7
+  #         status: ${{ job.status }}
+  #         token: ${{ secrets.CODECOV_TOKEN }}
+  #         codecov-files: behave-test-results/junit.xml
+  #         coverage-report: behave-test-results/coverage.xml
 
   # test-examples-partcad:
   #   name: "Examples (PartCAD)"
