Fixing build

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,54 +17,54 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  # test-pytest:
-  #   name: "Pytest"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
-  #       python-version: ["3.10", "3.11", "3.12"]
-  #   runs-on: ${{ matrix.os }}
-  #   if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
-  #   timeout-minutes: 30
+  test-pytest:
+    name: "Pytest"
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
+        python-version: ["3.10", "3.11", "3.12"]
+    runs-on: ${{ matrix.os }}
+    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
+    timeout-minutes: 30
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #     - uses: ./.github/actions/setup-test
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+      - uses: ./.github/actions/setup-test
 
-  #     - name: Test with pytest
-  #       env:
-  #         PYTHONPATH: partcad/src
-  #         PYTHONWARNINGS: ignore
-  #       shell: bash -l {0}
-  #       run: |
-  #         conda activate env-test
+      - name: Test with pytest
+        env:
+          PYTHONPATH: partcad/src
+          PYTHONWARNINGS: ignore
+        shell: bash -l {0}
+        run: |
+          conda activate env-test
 
-  #         mkdir -pv pytest-test-results
-  #         pytest -x -p no:error-for-skips -p no:warnings  --ignore-glob="openscad*" --dist no
-  #         coverage xml --data-file=./.coverage -o ./pytest-test-results/coverage.xml
-  #         conda deactivate
+          mkdir -pv pytest-test-results
+          pytest -x -p no:error-for-skips -p no:warnings  --ignore-glob="openscad*" --dist no
+          coverage xml --data-file=.coverage -o ./pytest-test-results/coverage.xml
+          conda deactivate
 
-  #     - name: Upload test results & coverage reports to github and codecov
-  #       uses: ./.github/actions/upload-test-results
-  #       with:
-  #         name: pytest-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #         path: pytest-test-results/
-  #         retention-days: 7
-  #         status: ${{ job.status }}
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         codecov-files: pytest-test-results/junit.xml
-  #         coverage-report: pytest-test-results/coverage.xml
+      - name: Upload test results & coverage reports to github and codecov
+        uses: ./.github/actions/upload-test-results
+        with:
+          name: pytest-test-results-${{matrix.os}}-${{matrix.python-version}}
+          path: pytest-test-results/
+          retention-days: 7
+          status: ${{ job.status }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+          codecov-files: pytest-test-results/junit.xml
+          coverage-report: pytest-test-results/coverage.xml
 
   test-behave:
     name: "Behave"
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
-        # os: [windows-latest]
-        # python-version: ["3.10"]
+        # TODO(clairbee): fix Windows support in behave (something is off with encodings)
+        # os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
+        os: [ubuntu-latest, macos-13, macos-latest]
         python-version: ["3.10", "3.11", "3.12"]
     runs-on: ${{ matrix.os }}
     if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
@@ -96,7 +96,7 @@ jobs:
             exit 1
           fi
           coverage combine || true
-          if ! coverage xml --data-file=./.coverage -o ./behave-test-results/coverage.xml; then
+          if ! coverage xml --data-file=.coverage -o ./behave-test-results/coverage.xml; then
             echo "Failed to generate coverage report"
             exit 1
           fi
@@ -113,51 +113,52 @@ jobs:
           codecov-files: behave-test-results/junit.xml
           coverage-report: behave-test-results/coverage.xml
 
-  # test-examples-partcad:
-  #   name: "Examples (PartCAD)"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
-  #       python-version: ["3.10", "3.11", "3.12"]
-  #   runs-on: ${{ matrix.os }}
-  #   if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
-  #   timeout-minutes: 90
+  test-examples-partcad:
+    name: "Examples (PartCAD)"
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
+        python-version: ["3.10", "3.11", "3.12"]
+    runs-on: ${{ matrix.os }}
+    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
+    timeout-minutes: 90
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #     - uses: ./.github/actions/setup-test
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+      - uses: ./.github/actions/setup-test
 
-  #     - name: Basic integration test for CLI (PartCAD examples)
-  #       shell: bash -l {0}
-  #       run: |
-  #         mkdir -pv examples-partcad-test-results
+      - name: Basic integration test for CLI (PartCAD examples)
+        shell: bash -l {0}
+        run: |
+          mkdir -pv examples-partcad-test-results
 
-  #         conda activate env-test
-  #         python -m pip install -U ./partcad ./partcad-cli
+          conda activate env-test
+          python -m pip install -U ./partcad ./partcad-cli
 
-  #         # BEGIN PARTCAD EXAMPLES
-  #         cd ./examples
-  #         coverage run --concurrency=thread -m partcad_cli.click.command --no-ansi list all -r
-  #         # Limit RAM usage by restricting the number of threads
-  #         coverage run --concurrency=thread -m partcad_cli.click.command --no-ansi --threads-max=2 test -r
-  #         coverage run --concurrency=thread -m partcad_cli.click.command --no-ansi --threads-max=2 render -r
-  #         # END PARTCAD EXAMPLES
+          # BEGIN PARTCAD EXAMPLES
+          cd ./examples
+          coverage run --data-file=.coverage.1 --concurrency=thread -m partcad_cli.click.command --no-ansi list all -r
+          # Limit RAM usage by restricting the number of threads
+          coverage run --data-file=.coverage.2 --concurrency=thread -m partcad_cli.click.command --no-ansi --threads-max=2 test -r
+          coverage run --data-file=.coverage.3 --concurrency=thread -m partcad_cli.click.command --no-ansi --threads-max=2 render -r
+          coverage combine
+          # END PARTCAD EXAMPLES
 
-  #         coverage xml --data-file=./.coverage -o ../examples-partcad-test-results/coverage.xml
-  #         conda deactivate
+          coverage xml --data-file=.coverage -o ../examples-partcad-test-results/coverage.xml
+          conda deactivate
 
-  #     - name: Upload test results & coverage reports to github and codecov
-  #       uses: ./.github/actions/upload-test-results
-  #       with:
-  #         name: examples-partcad-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #         path: examples-partcad-test-results/
-  #         retention-days: 7
-  #         status: ${{ job.status }}
-  #         token: ${{ secrets.CODECOV_TOKEN }}
-  #         codecov-files: examples-partcad-test-results/junit.xml
-  #         coverage-report: examples-partcad-test-results/coverage.xml
+      - name: Upload test results & coverage reports to github and codecov
+        uses: ./.github/actions/upload-test-results
+        with:
+          name: examples-partcad-test-results-${{matrix.os}}-${{matrix.python-version}}
+          path: examples-partcad-test-results/
+          retention-days: 7
+          status: ${{ job.status }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+          codecov-files: examples-partcad-test-results/junit.xml
+          coverage-report: examples-partcad-test-results/coverage.xml
 
   test-examples-all:
     name: "Examples (All)"
@@ -170,7 +171,7 @@ jobs:
         # python-version: ["3.10", "3.11", "3.12"]
     runs-on: ${{ matrix.os }}
     if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
-    timeout-minutes: 60
+    timeout-minutes: 90
 
     steps:
       - uses: actions/checkout@v4
@@ -188,14 +189,14 @@ jobs:
           # BEGIN ALL EXAMPLES
           cd ./examples
           coverage run --concurrency=thread -m partcad_cli.click.command --no-ansi list all -r //pub/examples
-          coverage xml --data-file=./.coverage -o ../examples-all-test-results/coverage.xml
-          rm -f ./.coverage
-          # Limit RAM usage by restricting the number of threads
+          coverage xml --data-file=.coverage -o ../examples-all-test-results/coverage.xml
+          rm -f .coverage
+          # TODO(clairbee): Limit RAM usage by restricting the number of threads?
           coverage run --concurrency=thread -m partcad_cli.click.command --no-ansi test -r --package //pub/examples
           # END ALL EXAMPLES
 
           # TODO(clairbee): Fix the coverage data from the test command above, and upload complete coverage data
-          coverage xml --data-file=./.coverage -o ../examples-all-test-results/coverage2.xml || true
+          coverage xml --data-file=.coverage -o ../examples-all-test-results/coverage2.xml || true
           ls -la ../examples-all-test-results
           conda deactivate
 
@@ -210,45 +211,47 @@ jobs:
           codecov-files: examples-all-test-results/junit.xml
           coverage-report: examples-all-test-results/coverage.xml
 
-  # test-pub-repo:
-  #   name: "Repo //pub"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       os: [ubuntu-24.04-l, windows-latest-l]
-  #       python-version: ["3.10", "3.12"]
-  #   runs-on: ${{ matrix.os }}
-  #   if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
-  #   timeout-minutes: 90
+  test-pub-repo:
+    name: "Repo //pub"
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-24.04-l, windows-latest-l]
+        python-version: ["3.10", "3.12"]
+    runs-on: ${{ matrix.os }}
+    if: ${{ !startsWith(github.event.head_commit.message, 'Version updated') }}
+    timeout-minutes: 90
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - uses: ./.github/actions/setup-all
-  #     - uses: ./.github/actions/setup-test
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-all
+      - uses: ./.github/actions/setup-test
 
-  #     - name: Test the entire repository
-  #       shell: bash -l {0}
-  #       run: |
-  #         mkdir -pv pub-repo-test-results
+      - name: Test the entire repository
+        shell: bash -l {0}
+        run: |
+          mkdir -pv pub-repo-test-results
 
-  #         conda activate env-test
-  #         python -m pip install -U ./partcad ./partcad-cli
+          conda activate env-test
+          python -m pip install -U ./partcad ./partcad-cli
 
-  #         # BEGIN PUBLIC REPO
-  #         cd examples
-  #         coverage run -m partcad_cli.click.command --no-ansi test -r --package //pub
-  #         # END PUBLIC REPO
+          # BEGIN PUBLIC REPO
+          cd examples
+          coverage run -m partcad_cli.click.command --no-ansi list all -r //pub
+          # TODO(clairbee): fix the failing packages first
+          # coverage run -m partcad_cli.click.command --no-ansi test -r --package //pub
+          # END PUBLIC REPO
 
-  #         # coverage xml --data-file=./.coverage -o ../pub-repo-test-results/coverage.xml
-  #         conda deactivate
+          coverage xml --data-file=.coverage -o ../pub-repo-test-results/coverage.xml
+          conda deactivate
 
-  #     # - name: Upload test results & coverage reports to github and codecov
-  #     #   uses: ./.github/actions/upload-test-results
-  #     #   with:
-  #     #     name: pub-repo-test-results-${{matrix.os}}-${{matrix.python-version}}
-  #     #     path: pub-repo-test-results/
-  #     #     retention-days: 7
-  #     #     status: ${{ job.status }}
-  #     #     token: ${{ secrets.CODECOV_TOKEN }}
-  #     #     codecov-files: pub-repo-test-results/junit.xml
-  #     #     coverage-report: pub-repo-test-results/coverage.xml
+      # - name: Upload test results & coverage reports to github and codecov
+      #   uses: ./.github/actions/upload-test-results
+      #   with:
+      #     name: pub-repo-test-results-${{matrix.os}}-${{matrix.python-version}}
+      #     path: pub-repo-test-results/
+      #     retention-days: 7
+      #     status: ${{ job.status }}
+      #     token: ${{ secrets.CODECOV_TOKEN }}
+      #     codecov-files: pub-repo-test-results/junit.xml
+      #     coverage-report: pub-repo-test-results/coverage.xml
